# Use postgres/example user/password credentials
version: '3.1'

services:
  webapp:
    build: ./NpgsqlPoc
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80

  db:
    image: postgres:15.3-alpine3.18
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: qpr
      POSTGRES_DB: qpr_db